CREATE TABLE candidatos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rg VARCHAR(255) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    vaga_id BIGINT,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id) ON DELETE CASCADE
);
